[package]
edition = "2021"
name = "etptypes"
version = "1.0.0+1.2"
authors = [
	"Lionel Untereiner <lionel.untereiner@geosiris.com>", 
    "Valentin Gauthier <valentin.gauthier@geosiris.com>"
]
categories = ["network-programming", "web-programming::websocket", "science"]
description = "Energistics Transport Protocol (ETP) Message types"
documentation = "https://github.com/geosiris-technologies/etptypes-rs/wiki"
homepage = "https://github.com/geosiris-technologies/etptypes-rs"
keywords = ["etp", "energistics"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/geosiris-technologies/etptypes-rs"

[dependencies]
bytes = "1.4.0"
derivative = "2.2.0"
avro-rs = "0.13.0"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.4.1", features = ["v4", "serde"]}
