[package]
name = "etptypes"
version = "1.0.0+1.2"
edition = "2021"
authors = [
	"Lionel Untereiner <lionel.untereiner@geosiris.com>", 
    "Valentin Gauthier <valentin.gauthier@geosiris.com>"
]
license = "MIT OR Apache-2.0"
keywords = ["etp", "energistics"]

[dependencies]
bytes = "1.4.0"
derivative = "2.2.0"
avro-rs = "0.13.0"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.4.1", features = ["v4", "serde"]}
