on:
  pull_request:
  push:
    branches:
      - main


name: Check and Lint

env:
  CODE_ROOT_DIR: gen/

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        working-directory: ${{ env.CODE_ROOT_DIR }}
        with:
          command: check --manifest-path ${{ env.CODE_ROOT_DIR }}

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        working-directory: ${{ env.CODE_ROOT_DIR }}
        with:
          command: fmt
          args: --all -- --check --manifest-path ${{ env.CODE_ROOT_DIR }}

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        working-directory: ${{ env.CODE_ROOT_DIR }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path ${{ env.CODE_ROOT_DIR }}
          name: Clippy Output