name: Cargo Build & Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CODE_ROOT_DIR: gen/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ${{ CODE_ROOT_DIR }}
      run: cargo build --verbose
    - name: Run tests
      working-directory: ${{ CODE_ROOT_DIR }}
      run: cargo test --verbose